version: "3"

services:
  web:
    build: .
    command: gunicorn --config gunicorn.conf.py haeahn_drf_be.wsgi:application
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
