version: "3"

services:
  web:
    build: .
    command: gunicorn --config gunicorn.conf.py haeahn_drf_be.wsgi:application
    volumes:
      - /var/www/haeahn-dfr-be/static/:/haeahn-drf-be/static/
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
