# Generated by Django 4.2.8 on 2024-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("menu_cd", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_collation="Korean_Wansung_CI_AS", max_length=100
                    ),
                ),
                ("is_used", models.BooleanField()),
            ],
            options={
                "db_table": "MENU",
                "managed": False,
            },
        ),
    ]
